#!/bin/sh

# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>

TEX_FILE_NAME=$(basename "$(git rev-parse --show-toplevel)")
tgt_name="MA_PolypSegCAN_Scheytt"

cp -f "$TEX_FILE_NAME".pdf ../"$tgt_name".pdf

exit 0
